name: Publish production

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      configuration: release
      version-suffix: ""

  publish-nuget:
    if: github.repository_owner == 'dequelabs' # don't attempt to publish from forks
    environment: nuget-production
    needs: ["build-and-test"]
    uses: ./.github/workflows/publish-nuget-packages.yml
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-github-release:
    if: github.repository_owner == 'dequelabs' # don't attempt to publish from forks
    environment: github-releases
    needs: ["publish-nuget"]
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: go get gopkg.in/aktau/github-release.v0

      - name: Download and run GitHub release script
        run: |
          curl https://raw.githubusercontent.com/dequelabs/attest-release-scripts/develop/src/node-github-release.sh -s -o ./node-github-release.sh
          chmod +x ./node-github-release.sh
          ./node-github-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PUBLISHING_GITHUB_TOKEN }}
          CIRCLE_PROJECT_USERNAME: ${{ github.repository_owner }}
          CIRCLE_PROJECT_REPONAME: ${{ github.event.repository.name }}
